name: Production Deployment

on:
  workflow_dispatch: # Allows the workflow to be run manually

env:
  AZURE_WEBAPP_NAME: "<your-web-app-name>" # Replace with your web app name
  AZURE_RESOURCE_GROUP: "<your-resource-group>" # Replace with your resource group name
  SOURCE_SLOT: "staging" # Slot to swap from
  TARGET_SLOT: "production" # Slot to swap to

jobs:
  swap-slots:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Log in to Azure
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 2: Swap Slots
    - name: Swap Slots
      run: |
        echo "Swapping slots from $SOURCE_SLOT to $TARGET_SLOT"
        az webapp deployment slot swap \
          --name $AZURE_WEBAPP_NAME \
          --resource-group $AZURE_RESOURCE_GROUP \
          --slot $SOURCE_SLOT \
          --target-slot $TARGET_SLOT
