name: Continuous Integration Build for BP calculator ASP.Net Core app

env:
  DOTNET_VERSION: '8.0.x'

on:
  push:
    branches: [ "main","sian/add-logic" ]
  workflow_dispatch:

jobs:
  ci-build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Build for Release
      run: dotnet build --configuration Release
    - name: Run unit tests
      run: dotnet test BPCalculatorTest/BPCalculatorTest.csproj --no-restore --configuration Release --collect:"XPlat Code Coverage" --collect "Code coverage" -l:trx
   
    - name: Publish Unit Test Results
      uses: dorny/test-reporter@v1
      with:
        artifact: ''
        name: MS Tests
        path: '**.trx'
        reporter: 'dotnet-trx'

    - name: Install ReportGenerator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool
      env:
       DOTNET_TOOL_ROOT: $HOME/.dotnet/tools

    - name: Publish code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: ./BPCalculatorTest/TestResults/**/coverage.cobertura.xml

    - name: Generate HTML Report
      run: |
        reportgenerator -reports:coverage.cobertura.xml -targetdir:coverage-report -reporttypes:Html

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage-report/