name: Dependency Check

on:
  pull_request:
  push:
    branches:
      - main
      - sian/tidy-up

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      # Checkout Project
      - name: Checkout Code
        uses: actions/checkout@v3

      # Run OWASP Dependency-Check
      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: BloodPressureApp
          scan: .
          format: HTML
          fail_on_severity: HIGH
