name: SmokeTest Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
     # debug trigger
      - name: Print GitHub Context
        run: echo "${{ toJson(github) }}"

      # Checkout Project
      - name: Checkout Code
        uses: actions/checkout@v3

      # Run OWASP Dependency-Check
      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: BloodPressureApp
          path: .
          format: HTML
          out: reports
          args: --failOn CVSS:8

      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: reports/dependency-check-report.html

